(require '_foreign)

;; https://github.com/clojure-emacs/clojure-mode
(@foreign/install-packages '(clojure-mode))
(require 'clojure-mode)

(add-to-list 'auto-mode-alist '("\\.clj$" . clojure-mode))
(add-to-list 'auto-mode-alist '("\\.cljs$" . clojure-mode))
(add-to-list 'auto-mode-alist '("\\.cljc$" . clojure-mode))
(add-to-list 'auto-mode-alist '("\\.boot$" . clojure-mode))

(define-clojure-indent
  (defroutes 1)
  (do 1)
  (proxy 1)
  (try 1)
  (do-template 1)
  (are 1)
  (do-sync 1)
  (GET 2)
  (POST 2)
  (PUT 2)
  (DELETE 2)
  (HEAD 2)
  (ANY 2)
  (context 1)
  (styled 2)
  (with-ctx-2d 2)
  (transformed 2)
  (path 2)
  (preserve-ctx 2)
  (within-ns 1)
  (tx 1)
  (ROUTE 2)
  (rpc 1)
  (rpc-let 1)
  (rpc+ 1)
  (rpc-let+ 1)
  (while-logged-in 0)
  (run* 1)
  (fresh 1)
  (matche 1)
  (matcha 1)
  (match 1)
  (|do 1)
  (matchv 2)
  (|let 1)
  (|case 1)
  
  ;; For Reify Health
  (render 1)
  (componentDidMount 1)
  (componentWillUnmount 1)
  (ui 1)
  (componentDidUpdate 1)
  (initLocalState 1)
  )

(require 'paredit)
(add-hook 'clojure-mode-hook 'paredit-mode)
(add-hook 'clojurescript-mode-hook 'paredit-mode)
(add-hook 'clojurec-mode-hook 'paredit-mode)

(require 'rainbow-delimiters)
(add-hook 'clojure-mode-hook #'rainbow-delimiters-mode)
(add-hook 'clojurescript-mode-hook #'rainbow-delimiters-mode)
(add-hook 'clojurec-mode-hook #'rainbow-delimiters-mode)

(require '_auto-fill)
(add-hook 'clojure-mode-hook #'_auto-fill/none)
(add-hook 'clojurescript-mode-hook #'_auto-fill/none)
(add-hook 'clojurec-mode-hook #'_auto-fill/none)

(remove-hook 'clojure-mode-hook #'turn-on-auto-fill)
(remove-hook 'clojurescript-mode-hook #'turn-on-auto-fill)
(remove-hook 'clojurec-mode-hook #'turn-on-auto-fill)

(provide '_clojure)
